"""Tooling-governance canaries for lint, MCP, size checks, and workflow docs."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).parent.parent


def _read(path: str) -> str:
    return (ROOT / path).read_text()


def test_ci_lint_uses_make_lint() -> None:
    ci = _read(".github/workflows/ci.yml")
    assert "run: make lint" in ci
    assert "flake8 src/ tests/" not in ci


def test_requirements_swap_flake8_for_ruff() -> None:
    requirements = _read("requirements.txt")
    assert "ruff" in requirements
    assert "flake8" not in requirements


def test_make_lint_runs_lint_and_size_checks() -> None:
    makefile = _read("Makefile")
    assert "bash scripts/lint-check.sh && bash scripts/size-check.sh" in makefile


def test_project_init_generates_stable_lint_header() -> None:
    script = _read("scripts/project-init.sh")
    tracked_lint = _read("scripts/lint-check.sh")
    header = "# Generated by project-init.sh. Re-run /project-init to regenerate."
    assert header in script
    assert header in tracked_lint


def test_bootstrap_fails_loudly_when_mcp_entry_missing() -> None:
    bootstrap = _read("scripts/bootstrap.sh")
    assert "ERROR: MCP memory server entry missing" in bootstrap
    assert "Run: npm install" in bootstrap
    assert (
        "This repository keeps MCP dependencies at the repo root alongside package-lock.json."
        in bootstrap
    )
    assert "npm install --silent" not in bootstrap


def test_start_mcp_memory_wrapper_guards_dependency() -> None:
    wrapper = _read("scripts/start-mcp-memory.sh")
    assert "MCP memory server dependency missing" in wrapper
    assert 'exec node "$ENTRY"' in wrapper
    opencode = _read("opencode.json")
    assert '"scripts/start-mcp-memory.sh"' in opencode


def test_size_check_uses_git_tracked_files_and_exemptions() -> None:
    size_check = _read("scripts/size-check.sh")
    assert "git', 'ls-files" in size_check
    assert "# EXEMPT: cohesive atomic unit" in size_check
    project_config = _read(".ai-layer/PROJECT_CONFIG.md")
    assert '"src/modules/lens_dialogue.py": 400' in project_config
    assert '"tests/test_pipeline.py": 400' in project_config


def test_existing_long_functions_are_marked_or_refactored() -> None:
    exempted = {
        "src/agent/orchestrator.py": "def run_pipeline(self, dataset_path: str) -> None:  # EXEMPT: cohesive atomic unit",
        "src/agent/pass1_runner.py": "def run_pass1(deid_path: str, config: dict) -> dict:  # EXEMPT: cohesive atomic unit",
        "src/agent/pass2_runner.py": "# EXEMPT: cohesive atomic unit",
        "src/modules/audit_emitter.py": "# EXEMPT: cohesive atomic unit",
        "src/modules/grounding_checker.py": "# EXEMPT: cohesive atomic unit",
        "src/modules/lens_dialogue.py": "# EXEMPT: cohesive atomic unit",
        "src/tools/review_cli.py": "# EXEMPT: cohesive atomic unit",
    }
    for path, marker in exempted.items():
        assert marker in _read(path), path
    assert "def _parse_args() -> argparse.Namespace:" in _read(
        "implementation docs/apply_devplan_deltas.py"
    )
    assert "def _build_ollama_request(" in _read("src/modules/ollama_client.py")


def test_sensitive_shell_guards_match_markdown_config() -> None:
    check = _read("scripts/check.sh")
    autonomy = _read("scripts/set-autonomy.sh")
    needle = 'grep -q "^- data_sensitivity: sensitive$" .ai-layer/PROJECT_CONFIG.md'
    assert needle in check
    assert needle in autonomy


def test_project_init_stale_tail_removed_and_design_stop_batched() -> None:
    project_init = _read(".opencode/commands/project-init.md")
    assert 'If "yes": skip to step 4 with the inferred values.' not in project_init
    assert "Ask three DESIGN_STOPs in order" not in project_init
    assert project_init.count("DESIGN_STOP") <= 6
    assert "combined DESIGN_STOP block" in project_init


def test_workflow_docs_include_commit_end_language() -> None:
    command_files = [
        ".opencode/agents/planner.md",
        ".opencode/commands/cold-review.md",
        ".opencode/commands/fix-report.md",
        ".opencode/commands/implement.md",
        ".opencode/commands/lint-evolve.md",
        ".opencode/commands/plan.md",
        ".opencode/commands/prime.md",
        ".opencode/commands/probe.md",
        ".opencode/commands/set-autonomy.md",
        ".opencode/commands/set-model.md",
        ".opencode/commands/summarize-decisions.md",
    ]
    for path in command_files:
        assert "clean git commit" in _read(path), path


def test_size_check_passes_on_current_repo() -> None:
    result = subprocess.run(
        ["bash", "scripts/size-check.sh"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
        env={**os.environ, "PYTHONPATH": str(ROOT / "src")},
    )
    assert result.returncode == 0, result.stdout + result.stderr
    assert "size-check: all passed" in result.stdout


def test_start_mcp_memory_fails_with_clear_message_when_entry_missing(
    tmp_path: Path,
) -> None:
    script = ROOT / "scripts" / "start-mcp-memory.sh"
    result = subprocess.run(
        ["bash", str(script)],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
        env={**os.environ, "PATH": os.environ.get("PATH", "")},
    )
    assert result.returncode == 1
    assert "MCP memory server dependency missing" in result.stderr
    assert "Run: npm install" in result.stderr


def test_ollama_request_builder_preserves_seed() -> None:
    sys.path.insert(0, str(ROOT / "src"))
    from modules.ollama_client import _build_ollama_request  # type: ignore

    request = _build_ollama_request(
        "http://localhost:11434",
        "demo-model",
        "system",
        "user",
        0.2,
        42,
    )
    assert request.full_url.endswith("/api/generate")
    payload = request.data.decode("utf-8")
    assert '"seed": 42' in payload
    assert '"temperature": 0.2' in payload
