#!/usr/bin/env bash
# Generated by project-init.sh. Re-run /project-init to regenerate.
set -uo pipefail
LINT_FAIL=0
echo '--- js-ts ---'
bash scripts/lint-adapters/js-ts.sh || LINT_FAIL=$((LINT_FAIL+1))
echo '--- python ---'
bash scripts/lint-adapters/python.sh || LINT_FAIL=$((LINT_FAIL+1))
echo '--- shell ---'
bash scripts/lint-adapters/shell.sh || LINT_FAIL=$((LINT_FAIL+1))
echo ''
[ "$LINT_FAIL" -eq 0 ] && echo 'lint: all passed' || { echo "lint: $LINT_FAIL failed"; exit 1; }
