#!/usr/bin/env bash
# scripts/verify-integrity.sh — checksum drift check on governance-critical files
#
# Tracks four files only: the executor MUST NOT modify these (per executor.md MUST NOT list).
# This script makes drift visible. It does not block writes — that would reintroduce the
# Magentica 1.x protected-file workflow that this rewrite explicitly removed.
#
# Baseline file: .ai-layer/integrity-baseline.txt (committed)
#   Format: one line per file, "<sha256>  <path>"
#   Generated by: bash scripts/verify-integrity.sh baseline
#   Regenerate after a planned, reviewed change to one of the tracked files.
#
# Exit: 0 = no drift | 1 = drift detected | 2 = baseline missing
set -uo pipefail

BASELINE=".ai-layer/integrity-baseline.txt"
ACTION="${1:-check}"

TRACKED=(
  "scripts/state.sh"
  "scripts/check.sh"
  "scripts/retry-budget.sh"
  ".opencode/plugins/gatekeeper.js"
)

case "$ACTION" in
  baseline)
    : > "$BASELINE"
    for f in "${TRACKED[@]}"; do
      if [ -f "$f" ]; then
        shasum -a 256 "$f" >> "$BASELINE"
      else
        echo "WARN: tracked file missing at baseline time: $f"
      fi
    done
    echo "integrity baseline written to $BASELINE"
    echo "Commit $BASELINE alongside the tracked files."
    ;;
  check)
    [ -f "$BASELINE" ] || { echo "INFO: integrity baseline not present — skipping (run: bash scripts/verify-integrity.sh baseline)"; exit 0; }
    DRIFT=0
    while IFS= read -r line; do
      [ -z "$line" ] && continue
      expected_hash=$(echo "$line" | awk '{print $1}')
      file=$(echo "$line" | awk '{print $2}')
      if [ ! -f "$file" ]; then
        echo "DRIFT: tracked file missing: $file"
        DRIFT=$((DRIFT+1))
        continue
      fi
      actual_hash=$(shasum -a 256 "$file" | awk '{print $1}')
      if [ "$expected_hash" != "$actual_hash" ]; then
        echo "DRIFT: $file (expected $expected_hash, got $actual_hash)"
        DRIFT=$((DRIFT+1))
      fi
    done < "$BASELINE"
    if [ "$DRIFT" -gt 0 ]; then
      echo ""
      echo "$DRIFT governance file(s) have drifted from baseline."
      echo "If the change was intentional and reviewed: bash scripts/verify-integrity.sh baseline"
      echo "If unexpected: investigate before continuing."
      exit 1
    fi
    echo "integrity: $(wc -l < "$BASELINE" | tr -d ' ') tracked files match baseline"
    ;;
  *)
    echo "Usage: bash scripts/verify-integrity.sh [baseline | check]"
    exit 2
    ;;
esac
